name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: macos-13
    steps: 
      - name: Print greeting
        run: echo "Hello World!!"
      - name: Print goodbye
        run: echo "Good bye!"
      - name: Multi-line print
        run: |
          echo "First Output"
          echo "Second Output"
